// ポータルに並べるアプリの一覧。新しいアプリを公開したら、ここに 1 件足すだけでよい。
//
//   id       : リポジトリ名（URL の /<id>/ と同じ）
//   name     : 短いアプリ名（manifest の short_name）
//   title    : 名前の後ろに付けるひとこと
//   desc     : 1〜2 文の説明
//   category : 'game'（ゲーム） / 'tool'（学び・ツール）
//   tags     : 小さく表示するラベル
//   icon     : 192px のアイコン（このサイトと同じオリジンなので /<id>/... で参照できる）
//   color    : アプリの theme_color（カードのアクセントに使う）
//
// 並び順がそのまま表示順。新しいものを上に足す。

window.TOFO_APPS = [
  {
    id: 'kagamigami',
    name: 'かがみがみ',
    title: '写真を切って並べる万華鏡',
    desc: '写真を鏡に映したように 4 枚並べ、細い短冊に切って端から交互に並べ直す。短冊の数を変えるだけで、万華鏡のような模様が次々に変わる。',
    category: 'tool',
    tags: ['画像', 'アート'],
    icon: '/kagamigami/icons/icon-192.png',
    color: '#18171c',
  },
  {
    id: 'tsumitate',
    name: '積立投資シミュレーター',
    title: '毎月の積み立て、何年後にいくら',
    desc: '毎月いくら入れて、年に何 % ふえたら、何年後にいくらになるかを計算する。入れたお金とふえたぶんを分けてグラフにするので、長く続けるほどふえ方が大きくなるのが見て分かる。',
    category: 'tool',
    tags: ['学び', 'お金'],
    icon: '/tsumitate/icons/icon-192.png',
    color: '#f3efe6',
  },
  {
    id: 'madoakari',
    name: 'まどあかり',
    title: '夜の窓をぜんぶ灯す',
    desc: '夜の建物の窓をタップして明かりをつける。押した窓と上下左右のとなりが一緒に切り替わるので、どこを押すかを考えて、なるべく少ない数で全部の窓を灯す。',
    category: 'game',
    tags: ['パズル'],
    icon: '/madoakari/icons/icon-192.png',
    color: '#141a33',
  },
  {
    id: 'sort-visualizer',
    name: '可視化ソート',
    title: '2 つの並べ替えで競走',
    desc: 'ばらばらの棒を、2 つのやり方で同時に並べ替えて競走させる。データの並び方を変えると勝ち負けが入れ替わり、比べた回数・動かした回数も数字で分かる。',
    category: 'tool',
    tags: ['学び', 'プログラミング'],
    icon: '/sort-visualizer/icons/icon-192.png',
    color: '#6c4bd1',
  },
  {
    id: 'shuttle-stop',
    name: 'SHUTTLE STOP',
    title: '行き来する布を止めて織る',
    desc: '左右に行き来する布の帯をタップで止めて、下の段に重ねて織り上げる。はみ出たぶんは切り落とされるので、ぴったり止めて細くしないのがこつ。',
    category: 'game',
    tags: ['アクション', 'タイミング'],
    icon: '/shuttle-stop/icons/icon-192.png',
    color: '#2d4a7a',
  },
  {
    id: 'langtons-ant',
    name: 'ラングトンのアリ',
    title: 'アリが描く終わらない模様',
    desc: '右か左に曲がるだけのアリが、歩くたびにマスの色を変えて模様を描く。曲がり方のルールを変えると、渦・左右対称・三角など、まったく違う形が育つ。',
    category: 'tool',
    tags: ['シミュレーション', '数学'],
    icon: '/langtons-ant/icons/icon-192.png',
    color: '#3f93b8',
  },
  {
    id: 'skewline',
    name: 'SKEWLINE',
    title: '置いてひねる立体の目並べ',
    desc: '立方体の面に印を置き、置いたあとに列を 1 回だけひねれる目並べ。ひねれば相手の列を崩すことも、自分の列を作ることもできる。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', '3D'],
    icon: '/skewline/icons/icon-192.png',
    color: '#ece6d9',
  },
  {
    id: 'swaystone',
    name: 'SWAYSTONE',
    title: '木と石と氷を積むタワー',
    desc: '木・石・氷のブロックを落として、土台の上に高く積み上げる。材質で重さとすべりやすさが違い、物理でゆれて崩れる。',
    category: 'game',
    tags: ['アクション', '物理'],
    icon: '/swaystone/icons/icon-192.png',
    color: '#d9a066',
  },
  {
    id: 'corner-reach',
    name: 'CORNER REACH',
    title: '角だけでつなぐ陣取り',
    desc: 'ブロックを角と角だけでつないで広げていく、CPU とのふたり陣取り。相手より多くのマスを盤に置けたら勝ち。',
    category: 'game',
    tags: ['ボードゲーム', '陣取り'],
    icon: '/corner-reach/icons/icon-192.png',
    color: '#2cc7b0',
  },
  {
    id: 'cube-othello',
    name: 'キューブ・オセロ',
    title: '立方体の6面で遊ぶオセロ',
    desc: '立方体の 6 つの面すべてが盤面のオセロ。縦横の列は辺を越えて隣の面へつながる。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', '3D'],
    icon: '/cube-othello/icons/icon-192.png',
    color: '#36a075',
  },
  {
    id: 'score-othello',
    name: '点数オセロ',
    title: '石に点数がついたオセロ',
    desc: '石の一つひとつに点数がついたオセロ。石の数ではなく点の合計で勝負する。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', 'オセロ'],
    icon: '/score-othello/icons/icon-192.png',
    color: '#f2c66d',
  },
  {
    id: 'insider',
    name: 'ワケシリ',
    title: '1台で遊ぶ会話と推理',
    desc: '1 台の端末を回して遊ぶ、4〜8 人の会話ゲーム。お題当てと、答えを知る者探しをアプリが進行する。',
    category: 'game',
    tags: ['パーティー', '推理'],
    icon: '/insider/icons/icon-192.png',
    color: '#ff4d5e',
  },
  {
    id: 'pentris',
    name: 'QUINTILE',
    title: 'ペントミノ落ち物パズル',
    desc: '5 マスのブロック「ペントミノ」で遊ぶ落ち物パズル。スコアを狙う AI 付き。',
    category: 'game',
    tags: ['パズル', '落ち物'],
    icon: '/pentris/icons/icon-192.png',
    color: '#6a9bff',
  },
  {
    id: 'coord-maze',
    name: 'COORD MAZE',
    title: '座標迷路',
    desc: '2〜12 次元の格子迷路を、座標だけで解くパズル。タップだけで遊べる。',
    category: 'game',
    tags: ['パズル', '迷路'],
    icon: '/coord-maze/icons/icon-192.png',
    color: '#9d7bff',
  },
  {
    id: 'gear-align',
    name: 'GEAR ALIGN',
    title: '歯車の向きを揃える',
    desc: '歯車を持ち上げて回し、合いマークの向きを全部揃えるパズル。全 80 コース。',
    category: 'game',
    tags: ['パズル'],
    icon: '/gear-align/icons/icon-192.png',
    color: '#d6a64c',
  },
  {
    id: 'Half-Cut',
    name: 'Half/Cut',
    title: 'ぴったり半分に切る',
    desc: '図形をスワイプ一本でぴったり半分に切るパズル。毎日 5 問のデイリーとエンドレス。',
    category: 'game',
    tags: ['パズル', 'デイリー'],
    icon: '/Half-Cut/icons/icon-192.png',
    color: '#e2582e',
  },
  {
    id: 'glyph-shift',
    name: 'ABILITILE',
    title: '絵柄が能力になるパズル',
    desc: 'ブロックを押すと絵柄の効果が発動し、能力はブロックと一緒に動く。盤面を目標の柄に揃えるとクリア。',
    category: 'game',
    tags: ['パズル'],
    icon: '/glyph-shift/icons/icon-192.png',
    color: '#b3a2ff',
  },
  {
    id: 'hue-hunter',
    name: 'DELTA HUE',
    title: '色相識別テスト',
    desc: '1 つだけ色相の違うマスを探して、見分けられる最小の色差を測る。',
    category: 'tool',
    tags: ['テスト', '色覚'],
    icon: '/hue-hunter/icons/icon-192.png',
    color: '#e24bc6',
  },
  {
    id: 'core-image-english',
    name: 'コアイメージ英語',
    title: '丸暗記しない英語',
    desc: '英単語・中学英文法・句動詞を、コアイメージの掛け算で理解する学習アプリ。',
    category: 'tool',
    tags: ['学習', '英語'],
    icon: '/core-image-english/icons/icon-192.png',
    color: '#d0662a',
  },
];
