// ポータルに並べるアプリの一覧。新しいアプリを公開したら、ここに 1 件足すだけでよい。
//
//   id       : リポジトリ名（URL の /<id>/ と同じ）
//   name     : 短いアプリ名（manifest の short_name）
//   title    : 名前の後ろに付けるひとこと
//   desc     : 1〜2 文の説明
//   category : 'game'（ゲーム） / 'tool'（学び・ツール）
//   tags     : 小さく表示するラベル
//   icon     : 192px のアイコン（このサイトと同じオリジンなので /<id>/... で参照できる）
//   color    : アプリの theme_color（カードのアクセントに使う）
//
// 並び順がそのまま表示順。新しいものを上に足す。

window.TOFO_APPS = [
  {
    id: 'one-off',
    name: 'ONE OFF',
    title: 'ひとりだけ、お題が少しちがう',
    desc: '1 台の端末を回して遊ぶ、3〜10 人の会話ゲーム。ひとりだけ少し違うお題を配られた人を（本人も気づいていない）、話のかみ合わなさから見つけ出す。',
    category: 'game',
    tags: ['パーティー', '1 台で'],
    icon: '/one-off/icons/icon-192.png',
    color: '#7ab8ff',
  },
  {
    id: 'high-floor',
    name: 'HIGH FLOOR',
    title: '一番損する人を出さない割り当て',
    desc: '部屋割りや係決めで、みんなが持ち点 100 点を行きたい先に配って、1 台の端末を回して入れる。一番点の低い人ができるだけ高くなる組み合わせを、端末の中だけで計算して出す。',
    category: 'tool',
    tags: ['割り当て', '公平'],
    icon: '/high-floor/icons/icon-192.png',
    color: '#7ee0b5',
  },
  {
    id: 'buyout',
    name: 'BUYOUT',
    title: '架空の会社を買い占める放置相場',
    desc: '架空の会社の株を売り買いして、配当で資産を増やす放置ゲーム。閉じている間も相場とニュースは動き続け、開くと留守の間の配当がまとめて入る。全 8 社の株を買い占めたらクリア。',
    category: 'game',
    tags: ['放置', '架空の相場'],
    icon: '/buyout/icons/icon-192.png',
    color: '#f2b64a',
  },
  {
    id: 'pair-carry',
    name: 'PAIR CARRY',
    title: '二つずつ運んで白黒に分ける',
    desc: '黒と白が交互に並んだ碁石を、となり合う 2 個ずつ空いた所へ動かして、黒と白に分けるパズル。組が増えるほど、どこから崩すかが難しくなる。1 列と市松の盤。',
    category: 'game',
    tags: ['パズル', 'ステージ'],
    icon: '/pair-carry/icons/icon-192.png',
    color: '#a3b8ad',
  },
  {
    id: 'cell-garden',
    name: 'CELL GARDEN',
    title: '生まれて消えるマスの模様',
    desc: 'マスがまわりの数だけで生まれたり消えたりをくり返す「ライフゲーム」。指で描くか、グライダーなどの有名な形を置いて、動き出す模様を眺める。',
    category: 'tool',
    tags: ['セル・オートマトン', '模様'],
    icon: '/cell-garden/icons/icon-192.png',
    color: '#a6e36e',
  },
  {
    id: 'arnolds-cat',
    name: 'ARNOLD\'S CAT',
    title: '混ぜた絵が必ず元に戻る',
    desc: '絵のマス目を決まった式で並べ替えて、ぐちゃぐちゃに混ぜる。何度もくり返すと、ある回数でぴったり元の絵に戻る。自分の写真でも試せる。',
    category: 'tool',
    tags: ['数学', '画像'],
    icon: '/arnolds-cat/icons/icon-192.png',
    color: '#e8933f',
  },
  {
    id: 'echo-reef',
    name: 'ECHO REEF',
    title: '鳴らして沈んだ岩を探す',
    desc: '海の底に沈んだ岩を、マスを鳴らして探す推理パズル。返ってくるのはいちばん近い岩までの距離だけなので、いくつもの音を重ねて、少ない回数で岩の場所を全部当てる。',
    category: 'game',
    tags: ['パズル', '今日の海'],
    icon: '/echo-reef/icons/icon-192.png',
    color: '#68d2e8',
  },
  {
    id: 'number-bench',
    name: 'NUMBER BENCH',
    title: '確率も体感時間も、すぐ計算',
    desc: '当たる確率や人生の体感時間など、ふと気になった数をすぐ計算する道具を集めた箱。つまみを動かすと、答えとグラフがその場で変わる。',
    category: 'tool',
    tags: ['数学', '計算'],
    icon: '/number-bench/icons/icon-192.png',
    color: '#e0603f',
  },
  {
    id: 'near-pin',
    name: 'NEAR PIN',
    title: 'ぴたり・おしいで番号を当てる',
    desc: '隠れた 3〜5 桁の数を当てる。予想すると、数字も場所も合った数「ぴたり」と、数字だけ合った数「おしい」が返ってくるので、手がかりを重ねて少ない回数でしぼり込む。',
    category: 'game',
    tags: ['パズル', '今日の 1 問'],
    icon: '/near-pin/icons/icon-192.png',
    color: '#ff8a65',
  },
  {
    id: 'wakuguri',
    name: 'わくぐり',
    title: '回る輪のすき間を通す',
    desc: '回っている輪のすき間を、玉がくぐり抜けるようにタップで撃ち出す。玉は輪を二度横切るので、入るときと出るときの両方ですき間が来る瞬間を読む。全 12 ステージ。',
    category: 'game',
    tags: ['タイミング', 'ステージ'],
    icon: '/wakuguri/icons/icon-192.png',
    color: '#9c6b36',
  },
  {
    id: 'cross-take',
    name: 'CROSS TAKE',
    title: '横と縦で数を取り合う',
    desc: '6×6 の数字の盤で、ひとりは横、ひとりは縦にだけ動いて数を取り合う。どの数を取るかで、相手が次に選べる列が決まる。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['対戦', 'CPU'],
    icon: '/cross-take/icons/icon-192.png',
    color: '#f2b035',
  },
  {
    id: 'yotsumawashi',
    name: 'よつまわし',
    title: '4本ずつ回して上に向ける',
    desc: '並んだ針を、4 本ずつまとめて回して全部真上に向けるパズル。1 本を直すととなりがずれるので、どこから回すかを考えて、なるべく少ない手数でそろえる。',
    category: 'game',
    tags: ['パズル', '回転'],
    icon: '/yotsumawashi/icons/icon-192.png',
    color: '#1f9a86',
  },
  {
    id: 'last-three',
    name: 'LAST THREE',
    title: '残るのは新しい 3 つだけ',
    desc: '○と×を交互に置いて、縦・横・斜めに 3 つ並べたら勝ち。ただし盤に残るのは自分の新しい 3 つだけで、4 つ目を置くと一番古い印が消える。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['対戦', 'CPU'],
    icon: '/last-three/icons/icon-192.png',
    color: '#f1cd6a',
  },
  {
    id: 'tap-quartet',
    name: 'TAP QUARTET',
    title: '指で遊ぶ 4 つの腕だめし',
    desc: '目かくしで 10 秒を当てる、合図にすばやく反応する、出た文字を打つ、ふたりで連打する。1 回 30 秒ほどの 4 つのミニゲームで、自己ベストを塗り替える。',
    category: 'game',
    tags: ['ミニゲーム', 'ふたり'],
    icon: '/tap-quartet/icons/icon-192.png',
    color: '#3f55c9',
  },
  {
    id: 'number-patterns',
    name: '数の模様',
    title: 'つまみで変わる数学の模様',
    desc: '素数のらせん・星形・マンデルブロ集合など、数と円が描く模様を切り替えて眺める。つまみで数を変えると、模様がその場で形を変える。',
    category: 'tool',
    tags: ['数学', '模様'],
    icon: '/number-patterns/icons/icon-192.png',
    color: '#7ee0c3',
  },
  {
    id: 'kazukakushi',
    name: 'かずかくし',
    title: '番号の見えない15パズル',
    desc: '数字の見えない 15 パズル。番号の 1 桁だけの白黒、正しい場所とのずれ、行と列の合計など、手がかりから番号を読み解いて元の並びに戻す。',
    category: 'game',
    tags: ['パズル', '15パズル'],
    icon: '/kazukakushi/icons/icon-192.png',
    color: '#e8e3d4',
  },
  {
    id: 'hirakibako',
    name: 'ひらきばこ',
    title: '開いた箱の六面をそろえる',
    desc: '箱を開いて平らにした図の上で、面を回して六つの面の色をそろえるパズル。まん中の面を囲む四つの面と、外をぐるりと囲む裏の面がつながって動く。2×2 と 3×3。',
    category: 'game',
    tags: ['パズル', '回転'],
    icon: '/hirakibako/icons/icon-192.png',
    color: '#e3a21a',
  },
  {
    id: 'irowa',
    name: 'いろわ',
    title: '三つの輪を回して色を戻す',
    desc: '重なった三つの輪を回して、玉の色を元の並びに戻すパズル。輪が重なる所の玉は二つの輪にまたがるので、一つを回すとほかの輪の並びも崩れる。',
    category: 'game',
    tags: ['パズル', '回転'],
    icon: '/irowa/icons/icon-192.png',
    color: '#ffe04d',
  },
  {
    id: 'meguribi',
    name: 'めぐりび',
    title: '灯りが止まった町へ行く',
    desc: '日本地図の上を灯りが町から町へかけめぐり、止めたところが次の旅先になる。全国 1,747 の市区町村から、地方や県でしぼったり、行った県を外したりして選べる。',
    category: 'tool',
    tags: ['旅', 'ルーレット'],
    icon: '/meguribi/icons/icon-192.png',
    color: '#0b1224',
  },
  {
    id: 'kagamigami',
    name: 'かがみがみ',
    title: '写真を切って並べる万華鏡',
    desc: '写真を鏡に映したように 4 枚並べ、細い短冊に切って端から交互に並べ直す。短冊の数を変えるだけで、万華鏡のような模様が次々に変わる。',
    category: 'tool',
    tags: ['画像', 'アート'],
    icon: '/kagamigami/icons/icon-192.png',
    color: '#18171c',
  },
  {
    id: 'tsumitate',
    name: '積立投資シミュレーター',
    title: '毎月の積み立て、何年後にいくら',
    desc: '毎月いくら入れて、年に何 % ふえたら、何年後にいくらになるかを計算する。入れたお金とふえたぶんを分けてグラフにするので、長く続けるほどふえ方が大きくなるのが見て分かる。',
    category: 'tool',
    tags: ['学び', 'お金'],
    icon: '/tsumitate/icons/icon-192.png',
    color: '#f3efe6',
  },
  {
    id: 'madoakari',
    name: 'まどあかり',
    title: '夜の窓をぜんぶ灯す',
    desc: '夜の建物の窓をタップして明かりをつける。押した窓と上下左右のとなりが一緒に切り替わるので、どこを押すかを考えて、なるべく少ない数で全部の窓を灯す。',
    category: 'game',
    tags: ['パズル'],
    icon: '/madoakari/icons/icon-192.png',
    color: '#141a33',
  },
  {
    id: 'sort-visualizer',
    name: '可視化ソート',
    title: '2 つの並べ替えで競走',
    desc: 'ばらばらの棒を、2 つのやり方で同時に並べ替えて競走させる。データの並び方を変えると勝ち負けが入れ替わり、比べた回数・動かした回数も数字で分かる。',
    category: 'tool',
    tags: ['学び', 'プログラミング'],
    icon: '/sort-visualizer/icons/icon-192.png',
    color: '#6c4bd1',
  },
  {
    id: 'shuttle-stop',
    name: 'SHUTTLE STOP',
    title: '行き来する布を止めて織る',
    desc: '左右に行き来する布の帯をタップで止めて、下の段に重ねて織り上げる。はみ出たぶんは切り落とされるので、ぴったり止めて細くしないのがこつ。',
    category: 'game',
    tags: ['アクション', 'タイミング'],
    icon: '/shuttle-stop/icons/icon-192.png',
    color: '#2d4a7a',
  },
  {
    id: 'langtons-ant',
    name: 'ラングトンのアリ',
    title: 'アリが描く終わらない模様',
    desc: '右か左に曲がるだけのアリが、歩くたびにマスの色を変えて模様を描く。曲がり方のルールを変えると、渦・左右対称・三角など、まったく違う形が育つ。',
    category: 'tool',
    tags: ['シミュレーション', '数学'],
    icon: '/langtons-ant/icons/icon-192.png',
    color: '#3f93b8',
  },
  {
    id: 'skewline',
    name: 'SKEWLINE',
    title: '置いてひねる立体の目並べ',
    desc: '立方体の面に印を置き、置いたあとに列を 1 回だけひねれる目並べ。ひねれば相手の列を崩すことも、自分の列を作ることもできる。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', '3D'],
    icon: '/skewline/icons/icon-192.png',
    color: '#ece6d9',
  },
  {
    id: 'swaystone',
    name: 'SWAYSTONE',
    title: '木と石と氷を積むタワー',
    desc: '木・石・氷のブロックを落として、土台の上に高く積み上げる。材質で重さとすべりやすさが違い、物理でゆれて崩れる。',
    category: 'game',
    tags: ['アクション', '物理'],
    icon: '/swaystone/icons/icon-192.png',
    color: '#d9a066',
  },
  {
    id: 'corner-reach',
    name: 'CORNER REACH',
    title: '角だけでつなぐ陣取り',
    desc: 'ブロックを角と角だけでつないで広げていく、CPU とのふたり陣取り。相手より多くのマスを盤に置けたら勝ち。',
    category: 'game',
    tags: ['ボードゲーム', '陣取り'],
    icon: '/corner-reach/icons/icon-192.png',
    color: '#2cc7b0',
  },
  {
    id: 'cube-othello',
    name: 'キューブ・オセロ',
    title: '立方体の6面で遊ぶオセロ',
    desc: '立方体の 6 つの面すべてが盤面のオセロ。縦横の列は辺を越えて隣の面へつながる。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', '3D'],
    icon: '/cube-othello/icons/icon-192.png',
    color: '#36a075',
  },
  {
    id: 'score-othello',
    name: '点数オセロ',
    title: '石に点数がついたオセロ',
    desc: '石の一つひとつに点数がついたオセロ。石の数ではなく点の合計で勝負する。CPU 対戦・ふたり対戦。',
    category: 'game',
    tags: ['ボードゲーム', 'オセロ'],
    icon: '/score-othello/icons/icon-192.png',
    color: '#f2c66d',
  },
  {
    id: 'insider',
    name: 'ワケシリ',
    title: '1台で遊ぶ会話と推理',
    desc: '1 台の端末を回して遊ぶ、4〜8 人の会話ゲーム。お題当てと、答えを知る者探しをアプリが進行する。',
    category: 'game',
    tags: ['パーティー', '推理'],
    icon: '/insider/icons/icon-192.png',
    color: '#ff4d5e',
  },
  {
    id: 'pentris',
    name: 'QUINTILE',
    title: 'ペントミノ落ち物パズル',
    desc: '5 マスのブロック「ペントミノ」で遊ぶ落ち物パズル。スコアを狙う AI 付き。',
    category: 'game',
    tags: ['パズル', '落ち物'],
    icon: '/pentris/icons/icon-192.png',
    color: '#6a9bff',
  },
  {
    id: 'coord-maze',
    name: 'COORD MAZE',
    title: '座標迷路',
    desc: '2〜12 次元の格子迷路を、座標だけで解くパズル。タップだけで遊べる。',
    category: 'game',
    tags: ['パズル', '迷路'],
    icon: '/coord-maze/icons/icon-192.png',
    color: '#9d7bff',
  },
  {
    id: 'gear-align',
    name: 'GEAR ALIGN',
    title: '歯車の向きを揃える',
    desc: '歯車を持ち上げて回し、合いマークの向きを全部揃えるパズル。全 80 コース。',
    category: 'game',
    tags: ['パズル'],
    icon: '/gear-align/icons/icon-192.png',
    color: '#d6a64c',
  },
  {
    id: 'Half-Cut',
    name: 'Half/Cut',
    title: 'ぴったり半分に切る',
    desc: '図形をスワイプ一本でぴったり半分に切るパズル。毎日 5 問のデイリーとエンドレス。',
    category: 'game',
    tags: ['パズル', 'デイリー'],
    icon: '/Half-Cut/icons/icon-192.png',
    color: '#e2582e',
  },
  {
    id: 'glyph-shift',
    name: 'ABILITILE',
    title: '絵柄が能力になるパズル',
    desc: 'ブロックを押すと絵柄の効果が発動し、能力はブロックと一緒に動く。盤面を目標の柄に揃えるとクリア。',
    category: 'game',
    tags: ['パズル'],
    icon: '/glyph-shift/icons/icon-192.png',
    color: '#b3a2ff',
  },
  {
    id: 'hue-hunter',
    name: 'DELTA HUE',
    title: '色相識別テスト',
    desc: '1 つだけ色相の違うマスを探して、見分けられる最小の色差を測る。',
    category: 'tool',
    tags: ['テスト', '色覚'],
    icon: '/hue-hunter/icons/icon-192.png',
    color: '#e24bc6',
  },
  {
    id: 'core-image-english',
    name: 'コアイメージ英語',
    title: '丸暗記しない英語',
    desc: '英単語・中学英文法・句動詞を、コアイメージの掛け算で理解する学習アプリ。',
    category: 'tool',
    tags: ['学習', '英語'],
    icon: '/core-image-english/icons/icon-192.png',
    color: '#d0662a',
  },
];
